### ISSUE TITLE
INPUT should hide clear button unless focused. 

### ISSUE THREAD

**Issue by TheOlajos** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#32]
Currently, when clear="true", the input always shows the clear button.

**Comment by BrayFlex** [comment]
I think this is combining 2 types of clearing but the proposed solution is worse than both.

field clearing can be required by a *user* or by *function*.

ex: 

*user*: If you had a form that automatically fills some of the form's fields out, users may want to edit or clear the prefilled results which means they need the ability to edit (via focus) or clear (via a button)

*function*: Now lets take into consideration the address bar in the browser, by function when focused it highlights all the text and any keypress will clear and replace it because by function it assumes you want to interact with it by typing

So the proposed solution is less clear to users and forces users to click 2 times for each input when required by user and 2 times when required by function, unless you just want to edit.
